### ISSUE TITLE
请问你这个小程序是怎么过审的？

### ISSUE THREAD

**Issue by wxsms** [zuoxiaobai/foodDiary#11]
我身为患者也做了一个类似的小程序，但是总是过不了审核。提示：1: 你好，你的小程序涉及提供备忘录、日记、记事服务，备忘录等属个人主体小程序未开放类目，建议申请企业主体小程序。

请问是有什么诀窍吗？

**Comment by zuoxiaobai** [comment]
我这个做的比较早，当时审核规则没这么严格。现在迭代版本也基本过不了审核，虽然可以通过配置接口进行服务升级、降级，来绕过审核，但也是违规的。个人主体还是建议放弃，使用企业主体来做会比较好

**Comment by wxsms** [comment]
嗯，感谢回复。
